
name: Build

on:
    push:
        branches:
          - master

jobs:
    release:
        name: build and release electron app
        runs-on: ${{ matrix.os }}
        
        strategy:
          fail-fast: false
          matrix:
            os: [windows-latest]
            
        steps:
          - name: Check out git repository
            uses: actions/checkout@v3.0.0
        
          - name: Install Node.js
            uses: actions/setup-node@v3.0.0
            with:
              node-version: "16"

          - name: Install Dependencies
            run: yarn install
        
          - name: Fix fluent-ffmpeg bug#573
            run: cp node_modules/fluent-ffmpeg/lib node_modules/fluent-ffmpeg/lib-cov -r
            
          - name: Build Electron App
            run: yarn package
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


          - name: upload artifacts
            uses: actions/upload-artifact@v3.0.0
            with:
              name: ${{ matrix.os }}
              path: dist

          - name: release
            uses: softprops/action-gh-release@v0.1.14
            if: startsWith(github.ref, 'refs/tags/')
            with:
              files: "dist/**"
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
